CREATE TABLE IF NOT EXISTS bennys_vehicle_mods (
  plate VARCHAR(12) NOT NULL,
  mods LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (plate)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
